sudo: required
language: node_js
node_js:
  - 10

services:
  - docker

cache:
  directories:
  - node_modules

script:
  - docker-compose up -d
  - npm run build
  - sleep 10
  - cypress run --record --key $CYPRESS_KEY
  - npm test
